#!/usr/bin/env bash
# updating packages

set -e

sudo apt-get update
sudo apt-get install -y nginx

# creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/blessi30ng permanent;"

sudo sed -i "s/server_name _;$string_for_replacement/" /etc/nginx/sites-enabled/default

#creating a custom error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom http response page

sudo sed -i "/server_name _;/a \\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# test for syntax errors
sudo nginx -t

# restarting nginx
sudo service nginx restart
