#!/usr/bin/env bash
# Fix web server to run Nginx listening on port 88808
sed -i "#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80//8080/g" /etc/nginx/sites-available/result/default
chmod 644 /etc//nginx/nginx.conf
pkill apache
sudo -u nginx service nginx start
