#!/usr/bin/env bash
# configs container to run nginx user
pkill -o apache2
chmod 77 /etc/nginx/nginx.conf
chown nginx:nginx -R /ect/nginx/
sed -i  "s/80/8080/g" /etc/nginx/sites-available/default
su nginx -c 'service nginx restart'
